feat: added husky and pre-commit hooks

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,6 +1,6 @@
 #!/bin/sh
 if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+    echo "Sorry, your commit message is invalid. please make sure to follow the conventional commit messages" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
